all:	TestDLL TestQueue TestStack

TestDLL:	TestDLL.cpp
	g++ -std=c++11 -Wall TestDLL.cpp -o TestDLL
	
TestQueue:	TestQueue.cpp
	g++ -std=c++11 -Wall TestQueue.cpp -o TestQueue
	
TestStack:	TestStack.cpp
	g++ -std=c++11 -Wall TestStack.cpp -o TestStack
	
clean:
	rm TestDLL TestQueue TestStack